### PR TITLE
Modular app

### PR DESCRIPTION
**Pull request by xarisd**
Danger! WIP 

**Only I (@xarisd) should merge this**

@HarrisSidiropoulos I created this PR as a place for changes and discussions/comments.

So we can "talk" here...

### CODE REVIEW

**Comment by xarisd** [comment]
@HarrisSidiropoulos I changed the ' POST /files/check' to return the new JSON format AND to accept JSON on the Request.
I put the details in the [README.md](https://github.com/polyptychon/sinatra-tus/blob/modular-app/README.md#post-check) so you can read it.

**Comment by xarisd** [comment]
@HarrisSidiropoulos I fixed the bugs and apply the 'OPTIONS' walkaround to all the requests.
I tested it with both PostMan and the tus-client.
Please test it to see if it's working OK.

**Comment by HarrisSidiropoulos** [comment]
Ok @xarisd works with tus-client

**Comment by xarisd** [comment]
@HarrisSidiropoulos I did remove the old code and clean up the 'Access-Control-Allow-Headers'

Please check this out...and :+1:  if everything is working correctly.

**Comment by HarrisSidiropoulos** [comment]
:+1:  @xarisd

**Pull request merged**
